### PR TITLE
dma.c: Improve override of 'from' host by MASQUERADE config setting

### LINKED ISSUE #114: MASQUERADE newhost does not override -f user@host
Some `mail` programs (such as the one from GNU mailutils) run sendmail with the `-f username@host` option. If `MASQUERADE` is set to just a hostname (so that `config.masquerade_user` is null and `config.masquerade_host` is non-null), the host from the `-f` option is used as-is and does not get replaced with the masqueraded host name when constructing the envelope 'from' address.

### PR DESCRIPTION
**Pull request by ian-abbott**
This allows a MASQUERADE config setting containing only a host name to override any host name set by the -f command line option or by the EMAIL environment variable.  Previously, that only worked if the MASQUERADE config setting also overrode the user name.

Fixes #114

### CODE REVIEW

**Comment by corecode** [comment]
There is a bit too much pointer arithmetic and confusing logic flow in there for my current taste.

I think we should start by stating what behavior we want regarding masquerade and address.

Clearly the current code (and the proposed change) are agglomerated ad-hoc code, which makes it hard to reason about.

**Comment by emaste** [comment]
> I think we should start by stating what behavior we want regarding masquerade and address.

I think what's documented already in dma.8 is reasonable.

**Comment by corecode** [comment]
-f sender
             Set sender address (envelope-from) to sender.  This over‐
             rides the value of the EMAIL environment variable, but is
             overridden by the ‘MASQUERADE’ config file setting.

and

           If ‘MASQUERADE’ does not contain a @ sign, the string is
           interpreted as a host name.  For example, setting ‘MASQUERADE’ to
           ‘john@’ on host ‘hamlet’ will send all mails as ‘john@hamlet’;
           setting it to ‘percolator’ will send all mails as
           ‘username@percolator’.

We could do this (and I think the PR does something very similar):

select (incomplete) address (highest priority first):
2. from `-f` arg
3. `EMAIL` env
4. just username, set elsewhere

Now split this address into user and host components.

If host is empty, use hostname, set elsewhere

Now apply masquerade:
- if masquerade_user is set, use that as user
- if masquerade_host is set, use that as host

Now reassemble address and return it.

It feels more intuitive to apply the masquerade last ("overriding") than interspersed with the user and host selection.

What do you think?

**Comment by ian-abbott** [comment]
I have an improved PR #117 more in line with the comments above.

**Comment by ian-abbott** [comment]
This PR is stale now that PR #117 has been merged, so closing it.

**Pull request closed without merging**
