### PR TITLE
fix 'cannt' typo in error message

### PR DESCRIPTION
**Pull request by emaste**

### CODE REVIEW

**Comment by corecode** [comment]
thanks!

**Comment by emaste** [comment]
Hrm, what has GitHub done? Commit 6748bdd wasn't included in the pull request when I submitted it :(

I pushed 6748bdd to my repo with the intent of discussing it before sending another PR for it.

**Comment by corecode** [comment]
you made a pull request for master, so it dutifully added the additional request.

the second one looked fine too - or do you want to modify it?

**Comment by emaste** [comment]
No, I'm happy with 6748bdd, I just didn't intend it to be included in the "fix a typo" PR. If you're happy with it then we're all set.

**Comment by emaste** [comment]
> you made a pull request for master, so it dutifully added the additional request.

It seems strange to me to do that for commits pushed to master after the pull request is created, but so be it.

**Pull request merged**
